name: 'Ansible'
description: 'Runs an Ansible playbook'
inputs:
  playbook:
    description: 'Playbook to run'
    required: true
  inventory:
    description: 'Ansible inventory to use'
    required: true
  limit:
    description: 'Limit to a specific host or group. Supports patterns specified here: https://docs.ansible.com/ansible/latest/inventory_guide/intro_patterns.html#common-patterns'
    required: false  

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.playbook }}      # $1 - playbook
    - ${{ inputs.inventory }}     # $2 - inventory
    - ${{ inputs.limit }}         # $3 - limit
