name: Build Backend

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      should_archive_objects:
        description: 'Should archive objects as GitHub artifact'
        type: boolean
        default: false
  push:
    branches: [ "master" ]
    paths:
      - '**/*.js'
      - '**/package.json'
      - '!**/frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    
    env: 
      WORKING_DIR: restaurant-reservation-gdsd

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './restaurant-reservation-gdsd/package-lock.json'
        
    - name: Install dependencies
      run: |
        cd $WORKING_DIR
        npm ci
        
    - name: Build
      run: |
        cd $WORKING_DIR
        npm run build --if-present
      
    - name: Test
      run: |
        cd $WORKING_DIR
        npm test --if-present
    
    - name: Archive objects
      if: ${{ github.event.inputs.should_archive_objects == 'true' }}
      uses: actions/upload-artifact@v3
      with:
        name: backend-build
        path: |
          $WORKING_DIR/libs/
          $WORKING_DIR/package*.json
          $WORKING_DIR/server.js
