name: Build and Test Frontend

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths:
      - '**/frontend/**/*.js'
      - '**/frontend/**/package.json'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    
    env: 
      WORKING_DIR: restaurant-reservation-gdsd/frontend/
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './restaurant-reservation-gdsd/frontend/package-lock.json'
        
    - name: Install dependencies
      run: |
        cd $WORKING_DIR
        npm ci
        
    - name: Build
      run: |
        cd $WORKING_DIR
        npm run build --if-present
      
    - name: Test
      run: |
        cd $WORKING_DIR
        npm test --if-present
