name: Build Frontend

on:
  workflow_dispatch:
    inputs:
      shoud_store_build:
        description: 'Should archive objects as GitHub artifact'
        type: boolean
        default: true

        
  workflow_call:
    inputs:
      shoud_store_build:
        description: 'Should archive objects as GitHub artifact'
        type: boolean
        default: false
  push:
    branches: [ "master" ]
    paths:
      - '**/frontend/**/*.js'
      - '**/frontend/**/package*.json'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    
    env: 
      WORKING_DIR: restaurant-reservation-gdsd/frontend/
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './restaurant-reservation-gdsd/frontend/package-lock.json'
        
    - name: Install dependencies
      run: |
        cd $WORKING_DIR
        npm ci
        
    - name: Build
      continue-on-error: true
      run: |
        cd $WORKING_DIR
        npm run build --if-present
      
    - name: Test
      continue-on-error: true
      run: |
        cd $WORKING_DIR
        npm test --if-present
        
    - name: Archive objects
      continue-on-error: true
      if: inputs.shoud_store_build == true
      uses: actions/upload-artifact@v3
      with:
        name: build-files 
        retention-days: 1
        path: |
          restaurant-reservation-gdsd/frontend/build
