name: Deploy code

on:
  workflow_dispatch:

jobs:
  build_backend:
    uses: ./.github/workflows/build_backend.yml
    with:
      shoud_store_build: true
  
  # build_frontend:

  deploy:
    needs: build_backend
    runs-on: ubuntu-latest

    
    steps:
    - uses: actions/checkout@v4.1.0
    
    - name: Download build files
      uses: actions/download-artifact@v3
      with:
        name: build-files

    # - name: Run ansible playbook to deploy code to server
    #   uses: dawidd6/action-ansible-playbook@v2.6.1
    #   with:
    #     playbook: deploy_web-server.yml
    #     vault_password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
    #     options: |
    #       --inventory hosts_azure_rm.yml
    #       --extra-vars "local_path=./ci-cd-restro-app"

    - name: Run ansible playbook to deploy code to server
      uses: ./.github/actions/ansible
      env:
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_SECRET: ${{ secrets.AZURE_SECRET }}
        AZURE_TENANT: ${{ secrets.AZURE_TENANT }}  
      with:
        playbook: deploy_web-server.yml
        inventory: hosts_azure_rm.yml
        


