name: Deploy code to server

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    
    # env: 
    #   WORKING_DIR: restaurant-reservation-gdsd/frontend/
      
    steps:
    - name: Build backend
      uses: ./.github/workflows/build_backend.yml
      with:
        shoud_store_build: true
