name: Deploy code to server

on:
  workflow_dispatch:

jobs:
  build_backend:
    uses: ./.github/workflows/build_backend.yml
    with:
      shoud_store_build: true
  
  # build_frontend:

  deploy:
    needs: build_backend
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

      
