name: Deploy code

on:
  workflow_dispatch:

jobs:
  build_backend:
    uses: ./.github/workflows/build_backend.yml
    with:
      shoud_store_build: true
  
  # build_frontend:

  deploy:
    needs: build_backend
    runs-on: ubuntu-latest

    
    steps:
    - uses: actions/checkout@v4.1.0
    
    - name: Download backend build
      uses: actions/download-artifact@v3
      with:
        name: backend-build

    - name: Download frontend build
      uses: actions/download-artifact@v3
      with:
        name: frontend-build
        path: ./frontend/build
        
    - name: Run ansible playbook to deploy code to server
      uses: ./.github/actions/ansible
      env:
        ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_SECRET: ${{ secrets.AZURE_SECRET }}
        AZURE_TENANT: ${{ secrets.AZURE_TENANT }}  
      with:
        playbook: site.yml
        inventory: hosts_azure_rm.yml
        limit: web
        


